# Generated by Django 5.0.7 on 2024-07-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detail',
            field=models.CharField(default=3, max_length=10000),
            preserve_default=False,
        ),
    ]
