# Generated by Django 5.0.7 on 2024-07-18 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_detail'),
        ('todo', '0002_task_priority'),
    ]

    operations = [
    ]
